### ISSUE TITLE
Kerala death data

### ISSUE THREAD

**Issue by srmsoumya** [DataKind-BLR/covid19bharat_scrapers#28]
Kerala: KL death data is available from a different source.

@kaizer1v add more details.

**Comment by rraman64** [comment]
tinkered to have working data extract of kerala deaths
use KLD (kerala deaths) & KLDBL (kerala death backlog) for virtual states 
modified python codes are attached here.
can be polished to match with uniform output (renamed to evade github restrictions).

[read_pdf.txt](https://github.com/DataKind-BLR/covid19bharat_scrapers/files/7492859/read_pdf.txt)
[scrapers.txt](https://github.com/DataKind-BLR/covid19bharat_scrapers/files/7492860/scrapers.txt)
[states..yaml.txt](https://github.com/DataKind-BLR/covid19bharat_scrapers/files/7492861/states.yaml.txt)
[statewise_get_data.txt](https://github.com/DataKind-BLR/covid19bharat_scrapers/files/7492862/statewise_get_data.txt)
.
