### ISSUE TITLE
KA not working both in bot and cli

### ISSUE THREAD

**Issue by rraman64** [DataKind-BLR/covid19bharat_scrapers#29]
fetching KA data {'name': 'Karnataka', 'state_code': 'KA', 'automatic': False, 'url_sources': ['https://twitter.com/DHFWKA'], 'type': 'pdf', 'url': '/tmp/ka.pdf', 'config': {'page': 5, 'start_key': 'Bagalakote', 'end_key': 'Total'}}
**no function definition in fn_map for state code KA**

**Comment by abhiramr** [comment]
Will fix it tonight

**Comment by kaizer1v** [comment]
KA doesn't publish PDFs anymore @abhiramr (see [twitter acc](https://twitter.com/DHFWKA/status/1455159299974393859/photo/1)) will have to try with image only

**Comment by rraman64** [comment]
I am on meeting.
Will join after 10pm

I will take care of KA and KL
Yesterday I did for both
Rajaraman
