### ISSUE TITLE
Global var to save state_code

### ISSUE THREAD

**Issue by kaizer1v** [DataKind-BLR/covid19bharat_scrapers#30]
https://github.com/DataKind-BLR/covid19bharat_scrapers/blob/af7db6ea25cac8324fabbe959ee4f7f6aaddcf72/telegram_bot/entry.py#L20

is using a global var to save the state code selected in the previous step. This is causing an issue to pull delta for the correct state when multiple users are using the bot.

**Comment by 1upkd** [comment]
Created PR [#32](https://github.com/DataKind-BLR/covid19bharat_scrapers/pull/32#issue-1041198423) for this. Please review. Was able to test for PDF with WB data and it worked. Could not test image because my Vision API isn't resolved yet
