### ISSUE TITLE
Submitting hospitalization data for some Indian cities/states

### ISSUE THREAD

**Issue by grill05** [DataKind-BLR/covid19bharat_scrapers#75]
Hi,

I've created a repo at https://github.com/grill05/misc_bed_availability_scraper that automates updation of hospitalization data for some cities. Currently, hospitalization (typical "normal" beds/O2/ICU/ventilator beds capacity/occupancy) is extracted daily around 12 PM for 
- delhi
- Gautam Buddh Nagar (noida)
- Chennai
- Pune
- Himachal Pradesh
- Madhya Pradesh
and is appended to the respective data.<city-name>.csv files (see https://github.com/grill05/misc_bed_availability_scraper/blob/master/data.chennai.csv for example)

This is likely to be useful for other researchers/analysts, especially as hospitalization may be a more important data-point than raw case-counts during the current wave (https://www.business-standard.com/article/current-affairs/hospitalisations-not-total-omicron-cases-should-concern-us-gautam-menon-121122001376_1.html)

Data for Mumbai (raw pdf bulletins, and an auto-updated csv) is extracted in another repo at https://github.com/grill05/mumbai_hospitalization_data/blob/master/mumbai.csv

Historical hospitalization data for delhi,mumbai,gurgaon and all districts of tamil nadu can be found at 

- delhi -> https://github.com/grill05/covid19india_data_parser/blob/master/csv_dumps/Delhi_Jun18_Oct27.csv
- mumbai -> https://github.com/grill05/covid19india_data_parser/blob/master/csv_dumps/mumbai.csv
- gurugram -> https://github.com/grill05/covid19india_data_parser/blob/master/csv_dumps/gurugram.csv
- Tamil Nadu all districts -> https://github.com/grill05/covid19india_data_parser/blob/master/csv_dumps/TN_hospitalizations.csv

I would also like to automate the extraction of Bengaluru's hospitalization data (from the city dashboard https://apps.bbmpgov.in/Covid19/en/bedstatus.php)

If a screenshot could be captured automatically daily, it should be possible to get O2/ICU/HDU occupancy using OCR

The trouble is that the automation mechanism I use (github actions workflows) doesn't seem to be  able to reach the IP address for the Microsoft PowerBI datasheet, that is the foundation for the Bengaluru dashboard app

Any help in this regard (automating daily screenshot capture of https://apps.bbmpgov.in/Covid19/en/bedstatus.php ) would be appreciated

thanks,

**Comment by s-mandeep** [comment]
I have tried one fix for that Bangalore data using selenium. It is working on my local repo. I don't know much about Github Actions, but it should work with that too.

I will be creating a pull request for your original repo. Consider those changes, should work most probably

**Comment by s-mandeep** [comment]
Nvm, this fix doesn't work with Github actions (I wonder why?). The only way to get this working is to host the selenium script somewhere else, I believe. Sorry, couldn't help! 😢

**Comment by grill05** [comment]
Thanks to @s-mandeep 's script, I added today's Bengaluru data (along with some past data I'd been archiving)

Bengaluru's hospitalization data (dec-21 onward) ->https://github.com/grill05/misc_bed_availability_scraper/blob/master/data.bengaluru.csv

In the meantime, I'll try to run the script on my machine daily, and update the bengaluru csv reasonably regularly

**Comment by s-mandeep** [comment]
So after a lot of tinkering, I managed to automate the Bengaluru data too. But will need historical data as you collected, since Actions will fetch only future data. Now you won't be required to run the script manually on your machine. I will create a new pull request in your repo after resolving the conflicts soon!

Also, hope your repo gets integrated into the covid19bharat repo as their maintainers haven't replied yet.

**Comment by grill05** [comment]
Thanks a lot

The historical data (updated upto Jan 5) can be found at https://github.com/grill05/misc_bed_availability_scraper/blob/master/data.bengaluru.csv

Basically, the script will just have to append at the bottom of this file

I've created a (limited) Indian hospitalization dashboard at https://grill05.github.io/india_covid_hospitalization_tracker/

It auto-generates plots daily using the raw csvs

Thread on the topic -> https://twitter.com/shananalla/status/1478813872173760515

I'll merge your PR once submitted.

**Comment by grill05** [comment]
I'll probably be adding a lot of code to scraper.py in [my repo ](https://github.com/grill05/misc_bed_availability_scraper/blob/master/scraper.py)

I'm planning to add code to auto-download/archive hospitalization data for Rajasthan,Bihar,Andhra Pradesh,Kerala,Chandigarh etc. So file will change a lot

I separated the selenium code you submitted for bengaluru in https://github.com/grill05/misc_bed_availability_scraper/blob/master/bengaluru.py

So may be better to use bengaluru.py as starting point for PR rather than scraper.py
